# GitHub actions workflow to build ACPIPatcher UEFI using VS2022 (Multi-arch)
#
# Copyright (c) 2023 - 2025, Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Build ACPIPatcher (Multi-Architecture)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [X64, IA32]
        target: [RELEASE, DEBUG]
    
    env:
      NASM_PREFIX: "C:\\Program Files\\NASM\\"
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install NASM
      run: choco install nasm

    - name: Setup Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch == 'IA32' && 'x86' || 'x64' }}

    - name: Clone EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
        
    - name: Build EDK2 Base Tools
      run: |
        cd edk2
        call edksetup.bat ForceRebuild
        
    - name: Build ACPIPatcher (${{ matrix.arch }}, ${{ matrix.target }})
      run: |
        set PACKAGES_PATH=%CD%\edk2;%CD%;
        set WORKSPACE=%CD%
        cd edk2
        call edksetup.bat
        build -t VS2022 -a ${{ matrix.arch }} -b ${{ matrix.target }} -p %WORKSPACE%\ACPIPatcherPkg\ACPIPatcherPkg.dsc
        
    - name: List build artifacts
      run: |
        echo "Build artifacts for ${{ matrix.arch }} ${{ matrix.target }}:"
        dir /S edk2\Build\ACPIPatcher\${{ matrix.target }}_VS2022\${{ matrix.arch }}\*.efi
        
    - name: Copy artifacts
      run: |
        set "BUILD_DIR=edk2\Build\ACPIPatcher\${{ matrix.target }}_VS2022\${{ matrix.arch }}"
        if exist "%BUILD_DIR%\ACPIPatcher.efi" copy "%BUILD_DIR%\ACPIPatcher.efi" ACPIPatcher-${{ matrix.arch }}-${{ matrix.target }}.efi
        if exist "%BUILD_DIR%\ACPIPatcherDxe.efi" copy "%BUILD_DIR%\ACPIPatcherDxe.efi" ACPIPatcherDxe-${{ matrix.arch }}-${{ matrix.target }}.efi
        dir *.efi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ACPIPatcher-${{ matrix.arch }}-${{ matrix.target }}-VS2022
        path: |
          *.efi
          edk2/Build/ACPIPatcher/**/*.txt
